---
- name: Creates directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: "u+rwx"

- name: Enable systemd socket for unix socket access
  ansible.builtin.systemd_service:
    name: docker.socket
    enabled: true

- name: Create an override for docker systemd service
  ansible.builtin.template:
    src: "override.j2"
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: "Restart Docker"
