---
- name: Example Usage
  hosts: all
  gather_facts: true # Disable if your role does not rely on facts
  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: geerlingguy.docker
      vars:
        docker_service_manage: true
        docker_daemon_options:
          log-opts:
            max-size: "50m"
            max-file: "3"
    - name: Secure Docker with client TLS
      ansible.builtin.include_role:
        name: rmenage.hardened_docker
      vars:
        rhd_server_cert_path: /etc/docker
        rhd_client_cert_path: /vagrant/docker-client-certs
        rhd_host: "127.0.0.1"
        rhd_secured_tcp_listener: yes
